/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(mvdr_sdr.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1b18365c68ac528f2a113fb64422bf30)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/mvdr/mvdr_sdr.h>
// pydoc.h is automatically generated in the build directory
#include <mvdr_sdr_pydoc.h>

void bind_mvdr_sdr(py::module& m)
{

    using mvdr_sdr    = ::gr::mvdr::mvdr_sdr;


    py::class_<mvdr_sdr, gr::sync_decimator,
        std::shared_ptr<mvdr_sdr>>(m, "mvdr_sdr", D(mvdr_sdr))

        .def(py::init(&mvdr_sdr::make),
           py::arg("freq"),
           py::arg("num_inputs"),
           py::arg("taps"),
           py::arg("target_prn"),
           D(mvdr_sdr,make)
        )
        



        ;




}








